'use client'

import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer'

interface ReportsPDFProps {
  summary: {
    totalRevenue: number
    totalOrders: number
    totalCustomers: number
    averageOrderValue: number
    profitMargin: number
  }
  growth: {
    revenueGrowth: number
    ordersGrowth: number
    customersGrowth: number
    profitGrowth: number
  }
  formatted: {
    currency: (n: number) => string
    percent: (n: number) => string
  }
}

const styles = StyleSheet.create({
  page: { padding: 24, fontSize: 12, color: '#111827' },
  header: { marginBottom: 16 },
  title: { fontSize: 20, fontWeight: 700 },
  subtitle: { fontSize: 12, color: '#6B7280' },
  grid: { flexDirection: 'row', gap: 12 },
  card: { flex: 1, borderWidth: 1, borderColor: '#E5E7EB', borderRadius: 6, padding: 8, marginBottom: 8 },
  label: { color: '#6B7280' },
  value: { fontSize: 14, fontWeight: 700 },
})

export default function ReportsPDF({ summary, growth, formatted }: ReportsPDFProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>Laporan & Analitik</Text>
          <Text style={styles.subtitle}>Ringkasan performa bisnis</Text>
        </View>

        <View style={styles.grid}>
          <View style={styles.card}>
            <Text style={styles.label}>Total Revenue</Text>
            <Text style={styles.value}>{formatted.currency(summary.totalRevenue)}</Text>
            <Text>Growth: +{growth.revenueGrowth}%</Text>
          </View>
          <View style={styles.card}>
            <Text style={styles.label}>Total Orders</Text>
            <Text style={styles.value}>{summary.totalOrders}</Text>
            <Text>Growth: +{growth.ordersGrowth}%</Text>
          </View>
        </View>

        <View style={styles.grid}>
          <View style={styles.card}>
            <Text style={styles.label}>Total Customers</Text>
            <Text style={styles.value}>{summary.totalCustomers}</Text>
            <Text>Growth: +{growth.customersGrowth}%</Text>
          </View>
          <View style={styles.card}>
            <Text style={styles.label}>AOV</Text>
            <Text style={styles.value}>{formatted.currency(summary.averageOrderValue)}</Text>
            <Text>Average Order Value</Text>
          </View>
          <View style={styles.card}>
            <Text style={styles.label}>Profit Margin</Text>
            <Text style={[styles.value, { color: '#059669' }]}>{formatted.percent(summary.profitMargin)}</Text>
            <Text>Growth: +{growth.profitGrowth}%</Text>
          </View>
        </View>

        <View>
          <Text style={styles.subtitle}>Generated by Susu Baroka Admin Panel</Text>
        </View>
      </Page>
    </Document>
  )
}